#!/bin/sh

PREREQ=""

prereqs()
{
echo "$PREREQ"
}

case $1 in
prereqs)
prereqs
exit 0
;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/losetup /sbin/
copy_exec /sbin/cryptsetup /sbin/
cp /etc/hostname ${DESTDIR}/etc/hostname
copy_exec /usr/bin/gpg /bin/
copy_exec /usr/bin/vi /bin/
copy_exec /lib/cryptsetup/askpass /lib/cryptsetup/
#(fear that the askpass of systemd could be different)
cp /usr/local/sbin/amkhlv-* ${DESTDIR}/sbin/

exit 0
~                       
