name:                amkhlv-tools
version:             0.1.0.0
github:              "githubuser/amkhlv-tools"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/amkhlv-tools#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  daily-exe:
    main:                daily.hs
    source-dirs:         app
    ghc-options:
    - -main-is Daily
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - amkhlv-tools
    - text
    - gtk3
    - yaml
    - bytestring
    - process
    - directory
    - filepath
  things-exe:
    main:                things.hs
    source-dirs:         app
    ghc-options:
    - -main-is Things
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - amkhlv-tools
    - text
    - gtk3
    - yaml
    - bytestring
    - process
    - directory
    - filepath      
  a:
    main:                a.hs
    source-dirs:         app
    ghc-options:
    - -main-is AYaml
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - amkhlv-tools
    - text
    - yaml
    - bytestring
    - process
    - directory
    - filepath
    - HsYAML
    - containers
    - ansi-terminal

tests:
  amkhlv-tools-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - amkhlv-tools
